# Generated by Django 6.0 on 2026-06-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_moderator_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_full_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
