# Generated by Django 6.0 on 2026-06-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('emoji', models.CharField(default='🍽', max_length=8)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('kcal', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('off', 'Open Food Facts'), ('user', 'User')], default='seed', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='nutrition_f_name_cad16d_idx'), models.Index(fields=['barcode'], name='nutrition_f_barcode_b3e40d_idx')],
            },
        ),
    ]
