# Generated by Django 6.0 on 2026-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_seed_bzhu_food_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('entry_date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('kcal', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user_email', 'entry_date', '-added_at'], name='nutrition_n_user_em_f10ca7_idx')],
            },
        ),
    ]
