# Generated by Django 6.0 on 2026-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_nutritionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very active')], default='light', max_length=16)),
                ('goal', models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain'), ('gain', 'Gain weight')], default='maintain', max_length=12)),
                ('kcal_goal', models.PositiveIntegerField(default=2200)),
                ('protein_goal', models.PositiveIntegerField(default=140)),
                ('fat_goal', models.PositiveIntegerField(default=70)),
                ('carbs_goal', models.PositiveIntegerField(default=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_email'],
                'indexes': [models.Index(fields=['user_email'], name='nutrition_n_user_em_6be8f8_idx')],
            },
        ),
    ]
