"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-zj7m&6fm&$(h$_#848i-y$c70_@uer&k#kj(v=+@48679w6q!t")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "planner",
    "mind",
    "ai_engine",
    "accounts",
    "diary",
    "habits",
    "nutrition",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.UserEmailMiddleware",  # Extract user email from header
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    'content-type',
    'x-user-email',
    'authorization',
    'accept',
    'origin',
]

ROOT_URLCONF = "config.urls"

# Disable APPEND_SLASH to avoid errors when Vercel strips trailing slashes
# This allows DELETE/PUT/PATCH requests without trailing slash to work
APPEND_SLASH = False

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cache configuration - using database cache (free, uses existing Postgres)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'


# ──────────────────────────────────────────────────────────────────────────────
# Image Generation (ai_engine.image_enrichment)
# Используется для обогащения команд `image_with_labels` от Llama.
# Провайдер: OpenRouter → Nano Banana 2
# (google/gemini-3.1-flash-image-preview, standard tier)
# ──────────────────────────────────────────────────────────────────────────────

# POST endpoint провайдера генерации изображений
IMAGE_GEN_API_URL = os.getenv(
    "IMAGE_GEN_API_URL",
    "https://openrouter.ai/api/v1/chat/completions",
)

# API-ключ. Для OpenRouter — тот же ключ, что OPENROUTER_API_KEY.
# В production задайте через переменную окружения IMAGE_GEN_API_KEY.
IMAGE_GEN_API_KEY = os.getenv(
    "IMAGE_GEN_API_KEY",
    os.getenv("OPENROUTER_API_KEY", ""),
)

# Идентификатор модели на OpenRouter
# "Nano Banana 2" / google/gemini-3.1-flash-image-preview — быстрее и дешевле
# чем BananaPro (gemini-3-pro-image-preview), используем для тестов/прода.
IMAGE_GEN_MODEL = os.getenv("IMAGE_GEN_MODEL", "google/gemini-3.1-flash-image-preview")

# Vision-фолбэк для grounding в illustration_pipeline. По умолчанию используем
# ту же модель, что и для генерации картинки, чтобы не разъезжались режимы и
# доступность в OpenRouter.
GROUNDING_FALLBACK_MODEL = os.getenv("GROUNDING_FALLBACK_MODEL", IMAGE_GEN_MODEL)

# Таймаут одного запроса к провайдеру (секунды)
IMAGE_GEN_TIMEOUT = int(os.getenv("IMAGE_GEN_TIMEOUT", "60"))

# Tier OpenRouter для маршрутизации запросов (standard / nitro)
IMAGE_GEN_TIER = os.getenv("IMAGE_GEN_TIER", "standard")

# Максимальное количество одновременных запросов к API генерации
# (актуально когда один ответ Llama содержит несколько image_with_labels команд)
IMAGE_GEN_MAX_WORKERS = int(os.getenv("IMAGE_GEN_MAX_WORKERS", "3"))

# Публичный URL сервиса (используется в HTTP-Referer при запросах к OpenRouter)
SITE_URL = os.getenv("SITE_URL", "https://timely.app")


# ──────────────────────────────────────────────────────────────────────────────
# Локальные модели на удалённой Mac Studio (через Tailscale, mlx_vlm.server +
# отдельный SAM2-сервис). Используются в ai_engine.illustration_pipeline для
# цепочки "banana → SAM2 → Qwen → SVG" и в ai_engine.ocr_views для OCR.
#
# Текущая раскладка портов на хосте MAC_STUDIO_HOST:
#   :8080 → mlx-community/Qwen3.6-27B-4bit   (общая VLM: vision + текст)
#   :8081 → mlx-community/GLM-OCR-bf16       (используется в ocr_views для OCR)
#   :8002 → SAM 2 (facebook/sam2-hiera-large), отдельный FastAPI-сервис,
#           контракт: POST /api/segment/ {image_base64, points, labels}
#                     → {mask_base64, score}
# ──────────────────────────────────────────────────────────────────────────────

MAC_STUDIO_HOST = os.getenv("MAC_STUDIO_HOST", "100.74.104.27")

# Qwen3.6-27B-4bit — универсальная локальная VLM (используется для семантической
# разметки/подписей объектов в illustration_pipeline; OpenAI-совместимый API).
QWEN_API_BASE_URL = os.getenv("QWEN_API_BASE_URL", f"http://{MAC_STUDIO_HOST}:8080/v1")
QWEN_API_KEY = os.getenv("QWEN_API_KEY", "sk-local")
QWEN_MODEL_NAME = os.getenv("QWEN_MODEL_NAME", "mlx-community/Qwen3.6-27B-4bit")
QWEN_TIMEOUT = int(os.getenv("QWEN_TIMEOUT", "60"))

# GLM-OCR / Smart Canvas Analyzer — существующая OpenAI-совместимая GLM
# интеграция. OCR и analyzer используют общий ai_engine.glm_client.
VISION_API_BASE_URL = os.getenv("VISION_API_BASE_URL", f"http://{MAC_STUDIO_HOST}:8081/v1")
VISION_API_KEY = os.getenv("VISION_API_KEY", "sk-local")
VISION_MODEL_NAME = os.getenv("VISION_MODEL_NAME", "mlx-community/GLM-OCR-bf16")
GLM_ANALYZER_MODEL_NAME = os.getenv("GLM_ANALYZER_MODEL_NAME", VISION_MODEL_NAME)
GLM_ANALYZER_TIMEOUT = int(os.getenv("GLM_ANALYZER_TIMEOUT", "60"))

# SAM 2 — точечная сегментация изображений (свой контракт, НЕ OpenAI-совместимый).
SAM2_API_URL = os.getenv("SAM2_API_URL", f"http://{MAC_STUDIO_HOST}:8002/api/segment/")
# Таймаут на запрос немалый: даже на уменьшенной копии изображения (см.
# ILLUSTRATION_SAM2_MAX_DIM) одна сегментация занимает несколько секунд,
# а сервис (см. ниже) почти не выигрывает от распараллеливания.
SAM2_TIMEOUT = int(os.getenv("SAM2_TIMEOUT", "120"))

# ──────────────────────────────────────────────────────────────────────────────
# Параметры построения векторных иллюстраций (illustration_pipeline)
#
# ВАЖНО про производительность SAM2-сервиса (измерено эмпирически на реальной
# сгенерированной иллюстрации 1408×768): время одного запроса критически
# зависит от РАЗРЕШЕНИЯ изображения — full-res ≈ 28 секунд на точку, а при
# нескольких ПАРАЛЛЕЛЬНЫХ запросах сервис уходит в массовые таймауты (он не
# распараллеливает инференс — судя по всему, единственное GPU-устройство).
# Поэтому: (1) перед отправкой в SAM2 уменьшаем длинную сторону картинки до
# ILLUSTRATION_SAM2_MAX_DIM (это ускоряет запрос ~в 10 раз: 28с → ~3с, при
# этом качество маски не страдает — контур всё равно упрощается на этапе
# построения SVG); маски затем растягиваются обратно к исходному разрешению.
# (2) держим ILLUSTRATION_SAM2_MAX_WORKERS низким (вплоть до 1 — без
# параллелизма), чтобы не перегружать сервис и не словить контеншн-замедление.
# ──────────────────────────────────────────────────────────────────────────────

# Сетка N×N стартовых точек — ПОДСТРАХОВКА к content-aware поиску объектов
# (см. illustration_pipeline._content_seed_points). Держим небольшим: основную
# работу выполняет content-aware детектор, сетка лишь подстраховывает на случай
# нетипичных изображений (текстурный фон и т.п.).
ILLUSTRATION_GRID_N = int(os.getenv("ILLUSTRATION_GRID_N", "3"))
ILLUSTRATION_MAX_OBJECTS = int(os.getenv("ILLUSTRATION_MAX_OBJECTS", "6"))

# Воркеры для Qwen-подписей — лёгкие vision-запросы на маленьких вырезанных
# фрагментах, параллелятся гораздо лучше, чем тяжёлая SAM2-сегментация.
ILLUSTRATION_MAX_WORKERS = int(os.getenv("ILLUSTRATION_MAX_WORKERS", "4"))

# Длинная сторона копии изображения, отправляемой в SAM2 (px). См. обоснование выше.
ILLUSTRATION_SAM2_MAX_DIM = int(os.getenv("ILLUSTRATION_SAM2_MAX_DIM", "384"))
# Параллелизм запросов к SAM2 — низкий специально (см. обоснование выше).
ILLUSTRATION_SAM2_MAX_WORKERS = int(os.getenv("ILLUSTRATION_SAM2_MAX_WORKERS", "2"))

# ── Логирование ──────────────────────────────────────────────────────
# По умолчанию Django показывает только WARNING+ от сторонних логгеров —
# из-за этого diagnostic-INFO ai_engine (классификация intent, режимы
# t2i/i2i, ход illustration-пайплайна) не попадал в консоль runserver,
# и отлаживать поток генерации приходилось вслепую.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "ai_engine": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
