"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-zj7m&6fm&$(h$_#848i-y$c70_@uer&k#kj(v=+@48679w6q!t")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "planner",
    "mind",
    "ai_engine",
    "accounts",
    "diary",
    "habits",
    "nutrition",
    "curriculum",
    "pomodoro",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.UserEmailMiddleware",  # Extract user email from header
    "ai_engine.middleware.AIUsageContextMiddleware",
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    'content-type',
    'x-user-email',
    'authorization',
    'accept',
    'origin',
]

ROOT_URLCONF = "config.urls"

# Disable APPEND_SLASH to avoid errors when Vercel strips trailing slashes
# This allows DELETE/PUT/PATCH requests without trailing slash to work
APPEND_SLASH = False

# Содержимое доски (ChatSession.canvas) приезжает одним JSON-телом, и
# иллюстрации лежат в нём как data-URI по сотне-другой килобайт каждая.
# Django по умолчанию режет тело на 2.5 МБ и отвечает RequestDataTooBig ДО
# входа во вью — то есть раньше, чем сериализатор успевает применить свой
# предел в 12 МБ. Из-за этого доска с несколькими иллюстрациями молча
# переставала сохраняться. Держим оба предела согласованными; последнее слово
# и понятная ошибка остаются за ai_engine.serializers.validate_canvas.
DATA_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cache configuration - using database cache (free, uses existing Postgres)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# ──────────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
# Curriculum: где лежат загруженные учебники
# ──────────────────────────────────────────────────────────────────────────────
# `curriculum.storage.get_storage()` читает ЭТУ настройку (не переменную
# окружения напрямую), поэтому без объявления здесь путь задать было нельзя, и
# файлы молча падали в BASE_DIR/.curriculum-storage.
#
# Важно для production: на Northflank файловая система контейнера эфемерная, и
# загруженные PDF пропадут при перезапуске. Это осознанное состояние на сейчас —
# `storage.S3StorageSettings` существует как точка перехода на объектное
# хранилище, но реализации пока нет.
CURRICULUM_STORAGE_ROOT = os.getenv(
    "CURRICULUM_STORAGE_ROOT", str(BASE_DIR / ".curriculum-storage")
)

# S3-совместимое хранилище (AWS S3, Cloudflare R2, MinIO).
#
# Переключатель ровно один: непустой `CURRICULUM_S3_BUCKET`. Ключи при этом
# необязательны — в облаке их часто выдаёт роль инстанса, и требовать их здесь
# значило бы запретить самый безопасный способ доступа.
#
# Для Cloudflare R2: `ENDPOINT_URL` вида
# `https://<account>.r2.cloudflarestorage.com`, регион `auto`, а
# `CURRICULUM_S3_SSE` оставить ПУСТЫМ — заголовок `ServerSideEncryption` R2 не
# принимает, и с ним каждая загрузка отвечала бы ошибкой. Объекты в R2 и так
# шифруются на стороне сервера.
#
# Под тест-раннером S3 выключен ВСЕГДА. Это не перестраховка: `.env`
# разработчика содержит боевые ключи R2, и тест, забывший подменить хранилище
# через `set_storage`, начал бы писать мусор в настоящий бакет. Тесты выбора
# backend включают флаг обратно через `@override_settings`.
CURRICULUM_S3_ENABLED = os.getenv(
    "CURRICULUM_S3_ENABLED", "true"
).strip().lower() not in ("0", "false", "no", "off")
if "test" in sys.argv:
    CURRICULUM_S3_ENABLED = False

CURRICULUM_S3_BUCKET = os.getenv("CURRICULUM_S3_BUCKET", "")
CURRICULUM_S3_REGION = os.getenv("CURRICULUM_S3_REGION", "")
CURRICULUM_S3_ENDPOINT_URL = os.getenv("CURRICULUM_S3_ENDPOINT_URL", "")
CURRICULUM_S3_ACCESS_KEY_ID = os.getenv("CURRICULUM_S3_ACCESS_KEY_ID", "")
CURRICULUM_S3_SECRET_ACCESS_KEY = os.getenv("CURRICULUM_S3_SECRET_ACCESS_KEY", "")
CURRICULUM_S3_SIGNED_URL_TTL = int(os.getenv("CURRICULUM_S3_SIGNED_URL_TTL", "300"))
CURRICULUM_S3_SSE = os.getenv("CURRICULUM_S3_SSE", "")

# Как запускается обработка документа: "auto" | "inline" | "celery".
# "auto" смотрит на наличие CELERY_BROKER_URL. Пока брокера нет, это "inline" —
# осознанный дефолт: забытая переменная окружения должна приводить к работающей
# обработке, а не к документу, навсегда зависшему в статусе «загружен».
CURRICULUM_INGEST_MODE = os.getenv("CURRICULUM_INGEST_MODE", "auto")

# Через сколько секунд без смены статуса джоб считается зависшим и документ можно
# ставить в обработку заново. Контейнер эфемерный: воркер может быть убит в любой
# момент, и без этого таймаута документ блокируется навсегда.
CURRICULUM_INGEST_STALE_AFTER_SECONDS = int(
    os.getenv("CURRICULUM_INGEST_STALE_AFTER_SECONDS", "1800")
)

# Размер фрагмента книги в токенах. Считает настоящий токенайзер
# (`curriculum/tokenizer.py`, cl100k_base), а не «символы делить на четыре»: на
# кириллице эвристика недосчитывает почти вдвое, и прежний лимит «350 токенов»
# на деле давал фрагменты около 630.
#
# TARGET — где стараемся закрыть фрагмент, MAX — граница, за которую не выходим,
# добавляя следующий блок. OVERLAP — сколько токенов предыдущего фрагмента
# повторяется в начале следующего, чтобы мысль на границе не пропадала из поиска.
# Перекрытие работает ТОЛЬКО внутри прозы одного раздела и никогда не пересекает
# границу задачи или решения.
CURRICULUM_CHUNK_TARGET_TOKENS = int(os.getenv("CHUNK_TARGET_TOKENS", "500"))
CURRICULUM_CHUNK_MAX_TOKENS = int(os.getenv("CHUNK_MAX_TOKENS", "650"))
CURRICULUM_CHUNK_OVERLAP_TOKENS = int(os.getenv("CHUNK_OVERLAP_TOKENS", "75"))

# Считать ли эмбеддинги вообще.
#
# Под тест-раннером — НИКОГДА. Причина конкретная и уже наступила: как только
# `EMBEDDING_MODEL` появился в `.env`, обработка книги в тестах пошла в сеть,
# и прогон curriculum вырос с 1.3 до 70 секунд на ретраях. Тесты не должны ни
# ходить наружу, ни тратить деньги, а патчить провайдера в каждом файле, где
# запускается пайплайн (их уже четыре), — значит гарантированно забыть про
# пятый.
#
# Тесты самого провайдера включают флаг обратно через
# `@override_settings(CURRICULUM_EMBEDDINGS_ENABLED=True)` и подставляют фейк.
CURRICULUM_EMBEDDINGS_ENABLED = os.getenv(
    "CURRICULUM_EMBEDDINGS_ENABLED", "true"
).strip().lower() not in ("0", "false", "no", "off")
if "test" in sys.argv:
    CURRICULUM_EMBEDDINGS_ENABLED = False

# Потолок числа фрагментов одной книги, для которых считаются эмбеддинги.
# Нужен не ради экономии — учебник на 400 страниц стоит около $0.004, — а чтобы
# ограничить патологический документ: `upload_validation.MAX_PAGES` допускает
# 1500 страниц, и вырожденная разбивка способна дать десятки тысяч фрагментов.
CURRICULUM_MAX_EMBEDDED_CHUNKS = int(
    os.getenv("CURRICULUM_MAX_EMBEDDED_CHUNKS", "4000")
)

# Брокер очереди. Пусто = очереди нет, обработка идёт внутри HTTP-запроса.
# ВНИМАНИЕ: Redis-аддон Northflank выдаёт схему `rediss://` (TLS), и kombu на ней
# требует `ssl_cert_reqs` — без него Celery падает при СТАРТЕ, а не на первой
# задаче. Подключать вместе с воркером в отдельной фазе.
CELERY_BROKER_URL = (
    os.getenv("CELERY_BROKER_URL", "")
    or os.getenv("REDIS_URL", "")
    or os.getenv("REDIS_MASTER_URL", "")  # так эту переменную называет Northflank
)

# Под тест-раннером брокера нет НИКОГДА — третий рубильник того же рода, что
# `CURRICULUM_EMBEDDINGS_ENABLED` и `CURRICULUM_S3_ENABLED`. Как только боевой
# `REDIS_MASTER_URL` появился в `.env`, восемь тестов упали разом: `resolve_mode`
# начал выбирать celery, и документы в inline-тестах перестали обрабатываться.
# Тесты очереди задают брокер сами через `@override_settings`.
if "test" in sys.argv:
    CELERY_BROKER_URL = ""

# TLS у брокера. Redis-аддон Northflank выдаёт схему `rediss://`, и без явного
# `ssl_cert_reqs` kombu падает при СТАРТЕ воркера, а не на первой задаче —
# отладить это по логам тяжело, потому что процесс не доживает до полезной
# работы. Проверка сертификата остаётся включённой: отключать её ради тишины в
# логах значит выбросить смысл TLS.
if CELERY_BROKER_URL.startswith("rediss://"):
    import ssl as _ssl

    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": _ssl.CERT_REQUIRED}

# Результатов у задач нет: хранилище результата — строка `IngestionJob`, её и
# опрашивает фронтенд. Отдельный result backend означал бы вторую копию статуса,
# которая рано или поздно разойдётся с первой.
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True

# Подтверждение задачи ПОСЛЕ выполнения: контейнер эфемерный, воркера могут убить
# посреди обработки книги, и сообщение должно вернуться в очередь.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = False

# По одной книге за раз на воркера. Обработка упирается в память (PDF целиком в
# RAM плюс растры страниц), и набирать себе очередь впрок — верный способ словить
# OOM-kill на середине второй книги.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 8

# Только JSON. Pickle позволил бы исполнить произвольный код из сообщения — при
# скомпрометированном Redis это мгновенный захват воркера.
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Жёсткий потолок на книгу: 1500 страниц с OCR не должны висеть вечно. Мягкий
# лимит на минуту раньше даёт задаче шанс записать в джоб причину остановки.
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "3600"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "3540"))

# ──────────────────────────────────────────────────────────────────────────────
# Adaptive lesson planning intake (existing OpenRouter text client)
# ──────────────────────────────────────────────────────────────────────────────
PLANNING_MODEL = os.getenv(
    "PLANNING_MODEL",
    os.getenv("TEXT_LLM_MODEL", "deepseek/deepseek-v4-flash"),
)
PLANNING_ENABLED = os.getenv("PLANNING_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
PLANNING_MAX_QUESTIONS = int(os.getenv("PLANNING_MAX_QUESTIONS", "4"))
PLANNING_REASONING_ENABLED = os.getenv(
    "PLANNING_REASONING_ENABLED", "true"
).lower() in {"1", "true", "yes", "on"}
# Caps the reasoning token budget instead of letting it run unbounded: a
# narrow/tricky topic can otherwise make the model "think" for most of
# PLANNING_MAX_TOKENS before it ever writes the question JSON, which is slow
# and burns tokens for a single adaptive follow-up question.
PLANNING_REASONING_EFFORT = os.getenv("PLANNING_REASONING_EFFORT", "low")
PLANNING_TIMEOUT = int(os.getenv("PLANNING_TIMEOUT", "20"))
PLANNING_MAX_TOKENS = int(os.getenv("PLANNING_MAX_TOKENS", "700"))


# ──────────────────────────────────────────────────────────────────────────────
# Image Generation (ai_engine.image_enrichment)
# Используется для обогащения команд `image_with_labels`.
# Провайдер: OpenRouter → Seedream 4.5 (ByteDance).
# ──────────────────────────────────────────────────────────────────────────────

# POST endpoint провайдера генерации изображений
IMAGE_GEN_API_URL = os.getenv(
    "IMAGE_GEN_API_URL",
    "https://openrouter.ai/api/v1/chat/completions",
)

# API-ключ. Для OpenRouter — тот же ключ, что OPENROUTER_API_KEY.
# В production задайте через переменную окружения IMAGE_GEN_API_KEY.
IMAGE_GEN_API_KEY = os.getenv(
    "IMAGE_GEN_API_KEY",
    os.getenv("OPENROUTER_API_KEY", ""),
)

# Идентификатор модели на OpenRouter ($0.04 за картинку).
# Предыдущая модель впечатывала в иллюстрацию псевдо-текст («Porgls»,
# «Courcta», «Fikicn», «Filek») даже с полным TEXT_FREE-контрактом и коротким
# терминальным запретом — и тем ломала контракт, по которому подписи
# накладываются отдельным слоем. Она же добавляла лишние стрелки, второй угол и
# внешнюю силу вопреки MECHANICS/INCLINED_PLANE-контрактам.
# NB: чисто image-модели (Seedream) обязаны попадать в `_is_image_only_model`
# (image_enrichment.py), иначе запрос уйдёт с modalities ["image", "text"] и
# провайдер ответит 404. То же касается любой новой модели.
# Gemini-3-pro-image мультимодальная (отдаёт и картинку, и текст), поэтому её
# туда добавлять НЕ нужно — проверено живым запросом.
#
# Проверять доступность модели нужно ТОЧЕЧНЫМ запросом
# GET /api/v1/models/<id>/endpoints, а НЕ поиском по листингу /api/v1/models:
# листинг отдаёт не весь каталог, и по нему легко ошибочно счесть живую модель
# снятой. bytedance-seed/seedream-4.5 в листинге отсутствует, но её endpoint
# `bytedance-seed/seedream-4.5-20251203` жив.
IMAGE_GEN_MODEL = os.getenv("IMAGE_GEN_MODEL", "google/gemini-3-pro-image")

# ── Выбор модели пользователем (ai_engine.image_models) ──────────────────────
# Пользователь переключает модель прямо на доске, поэтому `IMAGE_GEN_MODEL`
# перестал быть единственным источником истины: он остался дефолтом последней
# инстанции для вызовов, которые ничего не выбрали явно.
#
# ALLOWED — жёсткий allowlist. Model ID приходит с фронтенда, и доверять ему
# нельзя: без этого списка пользователь смог бы направить наш OpenRouter-ключ
# в любую модель каталога. Всё, чего нет в `ai_engine.image_models.IMAGE_MODELS`,
# игнорируется, поэтому опечатка в env не выдаст наружу нерабочий id.
IMAGE_GEN_ALLOWED_MODELS = os.getenv(
    "IMAGE_GEN_ALLOWED_MODELS",
    "bytedance-seed/seedream-4.5,openai/gpt-5.4-image-2",
)

# Дефолт для UI и для запросов без явного выбора. Приоритет выше, чем у
# IMAGE_GEN_MODEL, но значение обязано входить в allowlist — иначе берётся
# модель с флагом default из реестра.
IMAGE_GEN_DEFAULT_MODEL = os.getenv(
    "IMAGE_GEN_DEFAULT_MODEL",
    "bytedance-seed/seedream-4.5",
)

# Качество по умолчанию: low / medium / high. Намеренно НЕ "high" — оно молча
# удорожает каждую генерацию. Модели без поддержки качества параметр не
# получают вовсе.
IMAGE_GEN_QUALITY = os.getenv("IMAGE_GEN_QUALITY", "medium")

# Соотношение сторон генерации. Читалось в image_enrichment через
# getattr(settings, ...), но в settings отсутствовало — значение жило только
# во фолбэке и не настраивалось через env. Заведено явно.
IMAGE_GEN_ASPECT_RATIO = os.getenv("IMAGE_GEN_ASPECT_RATIO", "16:9")

# Vision-модель для grounding координат подписей в illustration_pipeline.
# ВАЖНО: это НЕ IMAGE_GEN_MODEL. Раньше значение наследовалось от него, но
# генератор картинок vision-chat не умеет, из-за чего грунтинг молча
# падал на неточные координаты. Нужна именно чат-модель со зрением.
GROUNDING_FALLBACK_MODEL = os.getenv("GROUNDING_FALLBACK_MODEL", "z-ai/glm-4.6v")

# Таймаут одного запроса к провайдеру (секунды)
IMAGE_GEN_TIMEOUT = int(os.getenv("IMAGE_GEN_TIMEOUT", "60"))

# Tier OpenRouter для маршрутизации запросов (standard / nitro)
IMAGE_GEN_TIER = os.getenv("IMAGE_GEN_TIER", "standard")

# Максимальное количество одновременных запросов к API генерации
# (актуально когда один ответ Llama содержит несколько image_with_labels команд)
IMAGE_GEN_MAX_WORKERS = int(os.getenv("IMAGE_GEN_MAX_WORKERS", "3"))

# Публичный URL сервиса (используется в HTTP-Referer при запросах к OpenRouter)
SITE_URL = os.getenv("SITE_URL", "https://timelyplan.me")


# ──────────────────────────────────────────────────────────────────────────────
# AI usage ledger and Timely-token limits
# ──────────────────────────────────────────────────────────────────────────────
# Text requests are charged by provider token count. Image requests that do not
# report token usage use a deterministic Timely-token charge per generated image.
AI_IMAGE_TOKEN_CHARGE = int(os.getenv("AI_IMAGE_TOKEN_CHARGE", "4000"))
AI_CONTEXT_TOKEN_LIMIT = int(os.getenv("AI_CONTEXT_TOKEN_LIMIT", "128000"))
AI_TOKEN_5H_LIMIT = int(os.getenv("AI_TOKEN_5H_LIMIT", "250000"))
AI_TOKEN_WEEKLY_LIMIT = int(os.getenv("AI_TOKEN_WEEKLY_LIMIT", "1000000"))
# Free is intentionally small. Pro preserves the previous global limits. Max
# gets 20x the rolling allowance of Pro while still retaining a hard ceiling.
AI_FREE_CONTEXT_TOKEN_LIMIT = int(
    os.getenv("AI_FREE_CONTEXT_TOKEN_LIMIT", "32000")
)
AI_FREE_TOKEN_5H_LIMIT = int(os.getenv("AI_FREE_TOKEN_5H_LIMIT", "25000"))
AI_FREE_TOKEN_WEEKLY_LIMIT = int(
    os.getenv("AI_FREE_TOKEN_WEEKLY_LIMIT", "100000")
)
AI_MAX_CONTEXT_TOKEN_LIMIT = int(
    os.getenv("AI_MAX_CONTEXT_TOKEN_LIMIT", "256000")
)
AI_MAX_TOKEN_5H_LIMIT = int(os.getenv("AI_MAX_TOKEN_5H_LIMIT", "5000000"))
AI_MAX_TOKEN_WEEKLY_LIMIT = int(
    os.getenv("AI_MAX_TOKEN_WEEKLY_LIMIT", "20000000")
)
AI_PRO_PRICE_USD = float(os.getenv("AI_PRO_PRICE_USD", "19.9"))
AI_MAX_PRICE_USD = float(os.getenv("AI_MAX_PRICE_USD", "199"))
AI_PLAN_LIMITS = {
    "free": {
        "label": "Free",
        "context": AI_FREE_CONTEXT_TOKEN_LIMIT,
        "five_hour": AI_FREE_TOKEN_5H_LIMIT,
        "weekly": AI_FREE_TOKEN_WEEKLY_LIMIT,
        "price_usd": 0.0,
        "usage_multiplier": 1,
    },
    "pro": {
        "label": "Pro",
        "context": AI_CONTEXT_TOKEN_LIMIT,
        "five_hour": AI_TOKEN_5H_LIMIT,
        "weekly": AI_TOKEN_WEEKLY_LIMIT,
        "price_usd": AI_PRO_PRICE_USD,
        "usage_multiplier": 10,
    },
    "max": {
        "label": "Max",
        "context": AI_MAX_CONTEXT_TOKEN_LIMIT,
        "five_hour": AI_MAX_TOKEN_5H_LIMIT,
        "weekly": AI_MAX_TOKEN_WEEKLY_LIMIT,
        "price_usd": AI_MAX_PRICE_USD,
        "usage_multiplier": 200,
    },
}
# Hard limits are enabled by default; set false only for an explicit A/B rollout.
AI_USAGE_ENFORCE_LIMITS = os.getenv("AI_USAGE_ENFORCE_LIMITS", "true").lower() in {
    "1",
    "true",
    "yes",
    "on",
}


# ──────────────────────────────────────────────────────────────────────────────
# Детерминированный путь научных схем (ai_engine.vector_pipeline)
# ──────────────────────────────────────────────────────────────────────────────
# Механику рисует не image-модель, а VectorRenderer: LLM отдаёт только семантику
# (surface/body/vector/angle_arc), геометрию целиком считает бэкенд. Так схема
# получается одинаковой при повторах, в кадре нет ни одной буквы, а подписи
# приезжают структурой с ТОЧНЫМИ якорями (середина древка каждой силы) —
# vision-грунтинг для них не нужен.
#
# По умолчанию ВЫКЛЮЧЕНО: путь покрывает пока только наклонную плоскость, всё
# остальное честно уходит в растр. Включать после проверки на живой доске.
ILLUSTRATION_VECTOR_PIPELINE = os.getenv("ILLUSTRATION_VECTOR_PIPELINE", "false")

# Новый A/B-переключатель имеет приоритет над прежним boolean-флагом.
# `legacy` не делает дополнительных Qwen-вызовов и остаётся production default.
DIAGRAM_PIPELINE_MODE = os.getenv("DIAGRAM_PIPELINE_MODE", "legacy")
DIAGRAM_PLANNER_MODEL = os.getenv(
    "DIAGRAM_PLANNER_MODEL",
    "qwen/qwen3.7-plus",
)
DIAGRAM_CRITIC_MODEL = os.getenv(
    "DIAGRAM_CRITIC_MODEL",
    "qwen/qwen3.7-plus",
)
DIAGRAM_PLANNER_ENABLED = os.getenv("DIAGRAM_PLANNER_ENABLED", "true")
DIAGRAM_CRITIC_ENABLED = os.getenv("DIAGRAM_CRITIC_ENABLED", "true")
DIAGRAM_MAX_RETRIES = int(os.getenv("DIAGRAM_MAX_RETRIES", "1"))
DIAGRAM_PLANNER_TIMEOUT = int(os.getenv("DIAGRAM_PLANNER_TIMEOUT", "45"))
DIAGRAM_CRITIC_TIMEOUT = int(os.getenv("DIAGRAM_CRITIC_TIMEOUT", "45"))
DIAGRAM_PLANNER_MAX_TOKENS = int(os.getenv("DIAGRAM_PLANNER_MAX_TOKENS", "2400"))
DIAGRAM_CRITIC_MAX_TOKENS = int(os.getenv("DIAGRAM_CRITIC_MAX_TOKENS", "1200"))

# Backward-compatible aliases for the first vector prototype. Diagram planning
# no longer inherits the global DeepSeek text model.
VECTOR_PLANNER_MODEL = os.getenv(
    "VECTOR_PLANNER_MODEL",
    DIAGRAM_PLANNER_MODEL,
)
VECTOR_PLANNER_TIMEOUT = int(
    os.getenv("VECTOR_PLANNER_TIMEOUT", str(DIAGRAM_PLANNER_TIMEOUT))
)


# ──────────────────────────────────────────────────────────────────────────────
# Локальные модели на удалённой Mac Studio (через Tailscale, mlx_vlm.server +
# отдельный SAM2-сервис). Используются в ai_engine.illustration_pipeline для
# цепочки "banana → SAM2 → Qwen → SVG" и в ai_engine.ocr_views для OCR.
#
# Текущая раскладка портов на хосте MAC_STUDIO_HOST:
#   :8080 → mlx-community/Qwen3.6-27B-4bit   (общая VLM: vision + текст)
#   :8081 → mlx-community/GLM-OCR-bf16       (БОЛЬШЕ НЕ ДЕФОЛТ для OCR: см.
#           блок Vision/OCR ниже — OCR по умолчанию идёт в Qwen3-VL через
#           OpenRouter, а этот порт остаётся опциональным локальным путём)
#   :8002 → SAM 2 (facebook/sam2-hiera-large), отдельный FastAPI-сервис,
#           контракт: POST /api/segment/ {image_base64, points, labels}
#                     → {mask_base64, score}
# ──────────────────────────────────────────────────────────────────────────────

MAC_STUDIO_HOST = os.getenv("MAC_STUDIO_HOST", "100.74.104.27")

# Хост выше живёт в CGNAT-диапазоне Tailscale (100.64.0.0/10) и из облачного
# контейнера не маршрутизируется вообще: SYN уходит в никуда, и клиент честно
# ждёт свой таймаут. Именно так прод и «сломался» — /api/ai/chat отдавал 504
# ровно через 60с (таймаут skills/router), потому что BOARD_LLM_BASE_URL на
# Northflank не задали и он молча ушёл на этот адрес. Тихий фолбэк допустим
# только в разработке; в проде отсутствие явного URL должно быть громким.
AI_ALLOW_LOCAL_LLM_FALLBACK = os.getenv(
    "AI_ALLOW_LOCAL_LLM_FALLBACK", "True" if DEBUG else "False"
).lower() in {"1", "true", "yes"}

# Qwen3.6-27B-4bit — универсальная локальная VLM (используется для семантической
# разметки/подписей объектов в illustration_pipeline; OpenAI-совместимый API).
QWEN_API_BASE_URL = os.getenv("QWEN_API_BASE_URL", f"http://{MAC_STUDIO_HOST}:8080/v1")
QWEN_API_KEY = os.getenv("QWEN_API_KEY", "sk-local")
QWEN_MODEL_NAME = os.getenv("QWEN_MODEL_NAME", "mlx-community/Qwen3.6-27B-4bit")
QWEN_TIMEOUT = int(os.getenv("QWEN_TIMEOUT", "60"))

# ──────────────────────────────────────────────────────────────────────────────
# Vision / OCR — Qwen3-VL через OpenRouter (ai_engine.glm_client)
#
# Раньше здесь стояла GLM-OCR на Mac Studio (:8081), а PRODUCT.md §7.4 называл
# целевой моделью self-hosted PaddleOCR-VL. От self-hosted пути отказались:
# развернуть его негде, а адрес Mac Studio лежит в CGNAT-диапазоне Tailscale
# (100.64.0.0/10) и из облачного контейнера не маршрутизируется вообще — SYN
# уходит в никуда, и запрос честно ждёт свой таймаут. Ровно так уже ломался чат
# (см. AI_ALLOW_LOCAL_LLM_FALLBACK выше), и OCR ломался бы так же.
#
# Поэтому по умолчанию — облачная Qwen3-VL через OpenRouter: тот же ключ, что у
# остальных моделей, никакого своего железа. Локальный путь никуда не делся,
# он просто перестал быть значением по умолчанию: задайте VISION_API_BASE_URL и
# VISION_MODEL_NAME, чтобы вернуться на Mac Studio.
#
# VISION_API_KEY отдельным ключом оставлен намеренно (можно развести квоты), но
# по умолчанию подхватывает OPENROUTER_API_KEY, иначе после смены базового URL
# запрос уходил бы с прежним «sk-local» и провайдер отвечал 401.
# ──────────────────────────────────────────────────────────────────────────────
VISION_API_BASE_URL = os.getenv("VISION_API_BASE_URL", "https://openrouter.ai/api/v1")
VISION_API_KEY = os.getenv("VISION_API_KEY") or os.getenv("OPENROUTER_API_KEY", "")
VISION_MODEL_NAME = os.getenv("VISION_MODEL_NAME", "qwen/qwen3-vl-32b-instruct")
# 32B-модель по сети отвечает дольше локальной: прежних 30 секунд не хватает.
VISION_TIMEOUT = int(os.getenv("VISION_TIMEOUT", "60"))
# Бинаризация Оцу в ocr_views.preprocess_and_encode настраивалась под выделенную
# OCR-модель: она давит полутона и оставляет чистый чёрный текст на белом. Qwen3-VL
# — универсальная VLM, и ей обычно легче читать изображение без порога (порог
# съедает слабый штрих карандаша), поэтому по умолчанию выключено.
# На чистом печатном тексте разницы нет — проверено вживую, оба режима дали
# одинаковую транскрипцию. Разница ожидается на реальном фото тетради; чтобы
# было чем сравнить, прежнее поведение оставлено в этом переключателе.
VISION_OCR_BINARIZE = os.getenv("VISION_OCR_BINARIZE", "0").strip().lower() in {"1", "true", "yes", "on"}
GLM_ANALYZER_MODEL_NAME = os.getenv("GLM_ANALYZER_MODEL_NAME", VISION_MODEL_NAME)
GLM_ANALYZER_TIMEOUT = int(os.getenv("GLM_ANALYZER_TIMEOUT", "60"))

# SAM 2 — точечная сегментация изображений (свой контракт, НЕ OpenAI-совместимый).
SAM2_API_URL = os.getenv("SAM2_API_URL", f"http://{MAC_STUDIO_HOST}:8002/api/segment/")
# Таймаут на запрос немалый: даже на уменьшенной копии изображения (см.
# ILLUSTRATION_SAM2_MAX_DIM) одна сегментация занимает несколько секунд,
# а сервис (см. ниже) почти не выигрывает от распараллеливания.
SAM2_TIMEOUT = int(os.getenv("SAM2_TIMEOUT", "120"))

# ──────────────────────────────────────────────────────────────────────────────
# Параметры построения векторных иллюстраций (illustration_pipeline)
#
# ВАЖНО про производительность SAM2-сервиса (измерено эмпирически на реальной
# сгенерированной иллюстрации 1408×768): время одного запроса критически
# зависит от РАЗРЕШЕНИЯ изображения — full-res ≈ 28 секунд на точку, а при
# нескольких ПАРАЛЛЕЛЬНЫХ запросах сервис уходит в массовые таймауты (он не
# распараллеливает инференс — судя по всему, единственное GPU-устройство).
# Поэтому: (1) перед отправкой в SAM2 уменьшаем длинную сторону картинки до
# ILLUSTRATION_SAM2_MAX_DIM (это ускоряет запрос ~в 10 раз: 28с → ~3с, при
# этом качество маски не страдает — контур всё равно упрощается на этапе
# построения SVG); маски затем растягиваются обратно к исходному разрешению.
# (2) держим ILLUSTRATION_SAM2_MAX_WORKERS низким (вплоть до 1 — без
# параллелизма), чтобы не перегружать сервис и не словить контеншн-замедление.
# ──────────────────────────────────────────────────────────────────────────────

# Сетка N×N стартовых точек — ПОДСТРАХОВКА к content-aware поиску объектов
# (см. illustration_pipeline._content_seed_points). Держим небольшим: основную
# работу выполняет content-aware детектор, сетка лишь подстраховывает на случай
# нетипичных изображений (текстурный фон и т.п.).
ILLUSTRATION_GRID_N = int(os.getenv("ILLUSTRATION_GRID_N", "3"))
ILLUSTRATION_MAX_OBJECTS = int(os.getenv("ILLUSTRATION_MAX_OBJECTS", "6"))

# Воркеры для Qwen-подписей — лёгкие vision-запросы на маленьких вырезанных
# фрагментах, параллелятся гораздо лучше, чем тяжёлая SAM2-сегментация.
ILLUSTRATION_MAX_WORKERS = int(os.getenv("ILLUSTRATION_MAX_WORKERS", "4"))

# Длинная сторона копии изображения, отправляемой в SAM2 (px). См. обоснование выше.
ILLUSTRATION_SAM2_MAX_DIM = int(os.getenv("ILLUSTRATION_SAM2_MAX_DIM", "384"))
# Параллелизм запросов к SAM2 — низкий специально (см. обоснование выше).
ILLUSTRATION_SAM2_MAX_WORKERS = int(os.getenv("ILLUSTRATION_SAM2_MAX_WORKERS", "2"))

# ── Логирование ──────────────────────────────────────────────────────
# По умолчанию Django показывает только WARNING+ от сторонних логгеров —
# из-за этого diagnostic-INFO ai_engine (классификация intent, режимы
# t2i/i2i, ход illustration-пайплайна) не попадал в консоль runserver,
# и отлаживать поток генерации приходилось вслепую.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "ai_engine": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "nutrition": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
