# Generated by Django 6.0 on 2026-01-02 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="dayplan",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="timerstate",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
