# Generated by Django 6.0 on 2026-01-03 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_block_id_alter_dayplan_id_alter_segment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                ("start_time", models.CharField(max_length=10)),
                ("end_time", models.CharField(max_length=10)),
                ("task", models.CharField(max_length=255)),
                ("color", models.CharField(default="#3b82f6", max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "subject_emoji",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "subject_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="dayplan",
            name="user_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dayplan",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="dayplan",
            unique_together={("user_email", "date")},
        ),
    ]
