# Generated by Django 6.0 on 2026-06-14 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_scheduleslot_dayplan_user_email_alter_dayplan_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('global_goal', 'Global Goal'), ('subgoal', 'Subgoal'), ('milestone', 'Milestone'), ('task', 'Task'), ('habit', 'Habit'), ('financial_goal', 'Financial Goal')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='not_started', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('planning_scale', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day')], max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=7, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planner.goal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalLink',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('depends_on', 'Depends On'), ('blocks', 'Blocks'), ('supports', 'Supports'), ('related_to', 'Related To'), ('parent_child', 'Parent-Child')], max_length=20)),
                ('strength', models.IntegerField(default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='planner.goal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='planner.goal')),
            ],
            options={
                'unique_together': {('source', 'target', 'type')},
            },
        ),
    ]
