# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_add_goal_and_goallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('global_goal', 'Global Goal'), ('goal', 'Goal'), ('subgoal', 'Subgoal'), ('milestone', 'Milestone'), ('task', 'Task'), ('habit', 'Habit'), ('financial_goal', 'Financial Goal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='planning_scale',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('quarter', 'Quarter'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('multi_year', 'Multi-year')], max_length=10, null=True),
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['parent_id', 'order_index', '-created_at']},
        ),
    ]
