# Generated by Django 6.0 on 2026-05-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_templatelesson'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diaryweek',
            new_name='diary_diary_user_em_ce5a25_idx',
            old_name='diary_diary_user_em_idx',
        ),
        migrations.RenameIndex(
            model_name='templatelesson',
            new_name='diary_templ_templat_385eff_idx',
            old_name='diary_tmpl_lesson_tpl_day_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklytemplate',
            new_name='diary_weekl_user_em_e5b618_idx',
            old_name='diary_weekl_user_em_idx',
        ),
    ]
