# Generated by Django 6.0 on 2026-08-11 08:51

import django.db.models.deletion
import studyplan.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0015_chat_without_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCommitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('kind', models.CharField(choices=[('school', 'Школа'), ('tutor', 'Репетитор'), ('exam', 'Экзамен'), ('family', 'Семейное событие'), ('other', 'Другое')], default='other', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Задано вручную'), ('chat', 'Разобрано из сообщения')], default='manual', max_length=16)),
                ('source_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'start_at'],
                'indexes': [models.Index(fields=['user_email', 'weekday'], name='studyplan_f_user_em_162b3e_idx'), models.Index(fields=['user_email', 'start_at'], name='studyplan_f_user_em_0c1d2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('objective', models.TextField(blank=True, default='')),
                ('activity_type', models.CharField(choices=[('theory', 'Теория'), ('guided_example', 'Разбор примера'), ('guided_practice', 'Практика с подсказками'), ('independent_practice', 'Самостоятельная практика'), ('homework', 'Домашняя работа'), ('review', 'Повторение'), ('assessment', 'Проверка'), ('project', 'Проект'), ('reading', 'Чтение'), ('coding', 'Программирование'), ('handwritten_problem', 'Задача на бумаге'), ('offline_activity', 'Занятие вне приложения')], default='theory', max_length=24)),
                ('workspace_type', models.CharField(choices=[('tutor_chat', 'Чат с тьютором'), ('smart_board', 'Научная доска'), ('paper_notebook', 'Тетрадь'), ('answer_form', 'Форма ответа'), ('built_in_code_editor', 'Встроенный редактор кода'), ('external_ide', 'Внешняя среда разработки'), ('book_reader', 'Читалка книги'), ('quiz', 'Опрос'), ('voice', 'Голос'), ('offline', 'Вне приложения'), ('project_workspace', 'Рабочее пространство проекта')], default='tutor_chat', max_length=24)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('fixed', models.BooleanField(default=False)),
                ('earliest_start', models.DateTimeField(blank=True, null=True)),
                ('latest_end', models.DateTimeField(blank=True, null=True)),
                ('allowed_weekdays', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('ready', 'Готов к началу'), ('in_progress', 'Идёт'), ('paused', 'Пауза'), ('completed', 'Завершён'), ('partially_completed', 'Завершён частично'), ('missed', 'Пропущен'), ('skipped', 'Пропущен намеренно'), ('rescheduled', 'Перенесён'), ('cancelled', 'Отменён')], db_index=True, default='scheduled', max_length=24)),
                ('detail_level', models.CharField(choices=[('outline', 'Контур'), ('detailed', 'Подробно')], default='outline', max_length=16)),
                ('source', models.CharField(choices=[('scheduler', 'Планировщик'), ('review', 'Повторение'), ('manual', 'Вручную'), ('recovery', 'Восстановление пропуска')], default='scheduler', max_length=16)),
                ('lesson_payload', models.JSONField(blank=True, default=dict)),
                ('mastery_criteria', models.TextField(blank=True, default='')),
                ('source_section_ids', models.JSONField(blank=True, default=list)),
                ('source_chunk_ids', models.JSONField(blank=True, default=list)),
                ('prerequisite_block_ids', models.JSONField(blank=True, default=list)),
                ('review_step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(default='scheduler', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_blocks', to='curriculum.courseplan')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_blocks', to='curriculum.coursemodule')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='studyplan.learningblock')),
                ('review_of_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_blocks', to='curriculum.coursetopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_blocks', to='curriculum.coursetopic')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('available_minutes', models.PositiveIntegerField()),
                ('energy_level', models.PositiveSmallIntegerField(default=0)),
                ('stress_level', models.PositiveSmallIntegerField(default=0)),
                ('has_urgent_task', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='studyplan.learningblock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generation_source', models.CharField(default='deterministic', max_length=32)),
                ('scheduling_version', models.CharField(default='1.0.0', max_length=16)),
                ('pacing_snapshot', models.JSONField(blank=True, default=dict)),
                ('conflict_report', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.courseplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='learningblock',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='studyplan.studyschedule'),
        ),
        migrations.CreateModel(
            name='WeeklyScheduleTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(default='Мой ритм', max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_minutes_per_day', models.PositiveIntegerField(default=0)),
                ('max_minutes_per_week', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(default='student', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email', 'active'], name='studyplan_w_user_em_371fbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('allowed_activity_types', models.JSONField(blank=True, default=studyplan.models.default_activity_types)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('fixed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='studyplan.weeklyscheduletemplate')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='studyplan.weeklyscheduletemplate'),
        ),
        migrations.CreateModel(
            name='LearningBlockResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('completion_reason', models.CharField(blank=True, default='', max_length=64)),
                ('result', models.CharField(choices=[('completed', 'Завершён'), ('partial', 'Частично'), ('failed', 'Не получилось'), ('abandoned', 'Брошен')], default='completed', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('mastery_result', models.CharField(blank=True, default='', max_length=32)),
                ('error_types', models.JSONField(blank=True, default=list)),
                ('focus_events', models.JSONField(blank=True, default=list)),
                ('student_feedback', models.TextField(blank=True, default='')),
                ('artifact_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='studyplan.learningblock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email', '-created_at'], name='studyplan_l_user_em_265b14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('base_version', models.PositiveIntegerField()),
                ('proposed_version', models.PositiveIntegerField()),
                ('requested_by', models.CharField(choices=[('student', 'Ученик'), ('ai', 'AI'), ('system', 'Система')], default='student', max_length=16)),
                ('request_text', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('proposed', 'Предложена'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('reverted', 'Отменена'), ('expired', 'Устарела')], db_index=True, default='proposed', max_length=16)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('inverse_diff', models.JSONField(blank=True, default=dict)),
                ('impact', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='studyplan.studyschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schedule', 'status'], name='studyplan_s_schedul_fdf8bb_idx'), models.Index(fields=['user_email', '-created_at'], name='studyplan_s_user_em_cc4d64_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='learningblock',
            index=models.Index(fields=['schedule', 'start_at'], name='studyplan_l_schedul_2530cf_idx'),
        ),
        migrations.AddIndex(
            model_name='learningblock',
            index=models.Index(fields=['user_email', 'start_at'], name='studyplan_l_user_em_1fbd28_idx'),
        ),
        migrations.AddIndex(
            model_name='learningblock',
            index=models.Index(fields=['user_email', 'status'], name='studyplan_l_user_em_85a327_idx'),
        ),
        migrations.AddIndex(
            model_name='learningblock',
            index=models.Index(fields=['schedule', 'status'], name='studyplan_l_schedul_be93ca_idx'),
        ),
        migrations.AddIndex(
            model_name='templateslot',
            index=models.Index(fields=['template', 'weekday'], name='studyplan_t_templat_bce7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='studyschedule',
            index=models.Index(fields=['user_email', 'status'], name='studyplan_s_user_em_7be3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='studyschedule',
            index=models.Index(fields=['course_plan', 'status'], name='studyplan_s_course__1ffdc0_idx'),
        ),
    ]
