# Generated by Django 6.0 on 2026-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='freeze_budget',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
