# Generated by Django 6.0 on 2026-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('kind', models.CharField(choices=[('focus', 'Фокус'), ('break', 'Перерыв')], default='focus', max_length=8)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('seconds', models.PositiveIntegerField()),
                ('planned_seconds', models.PositiveIntegerField()),
                ('preset_focus_min', models.PositiveSmallIntegerField()),
                ('preset_break_min', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user_email', '-started_at'], name='pomodoro_fo_user_em_22bc50_idx')],
            },
        ),
    ]
