# Generated by Django 6.0 on 2026-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
