# Generated by Django 6.0 on 2026-08-09

from django.db import migrations, models


INGESTION_STATUS_CHOICES = [
    ("uploaded", "Загружен"),
    ("queued", "В очереди"),
    ("validating", "Проверка"),
    ("extracting_native_text", "Извлечение текста"),
    ("classifying_pages", "Классификация страниц"),
    ("ocr", "Распознавание"),
    ("reconstructing_structure", "Восстановление структуры"),
    ("extracting_blocks", "Извлечение блоков"),
    ("chunking", "Разбиение на фрагменты"),
    ("indexing", "Индексация"),
    ("quality_check", "Проверка качества"),
    ("ready", "Готов"),
    ("failed", "Ошибка"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_block_page_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="ingestion_status",
            field=models.CharField(
                choices=INGESTION_STATUS_CHOICES,
                db_index=True,
                default="uploaded",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ingestionjob",
            name="status",
            field=models.CharField(
                choices=INGESTION_STATUS_CHOICES,
                db_index=True,
                default="uploaded",
                max_length=32,
            ),
        ),
    ]
