# Generated by Django 6.0 on 2026-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_document_section_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='duration_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
