# Generated by Django 6.0 on 2026-08-10 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_course_topic_duration_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(default='medium', max_length=24)),
                ('is_teachable', models.BooleanField(default=True)),
                ('content_statistics', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('processing_version', models.CharField(default='1.3.0', max_length=16)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_profiles', to='curriculum.document')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='curriculum.documentsection')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'content_hash'], name='curriculum__documen_0dcf3f_idx')],
            },
        ),
    ]
