# Generated by Django 6.0 on 2026-08-11 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_processing_version_1_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='curriculum.learninggoal')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_email', 'goal', '-updated_at'], name='curriculum__user_em_49b92f_idx')],
            },
        ),
    ]
