# Generated by Django 6.0 on 2026-08-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_subject_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchat',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='curriculum.learninggoal'),
        ),
    ]
