# Generated by Django 6.0 on 2026-08-12 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_chat_without_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('kind', models.CharField(choices=[('link', 'Ссылка'), ('practice_set', 'Практис-тесты'), ('problem_set', 'Задачник'), ('custom', 'Своё')], default='link', max_length=20)),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('note', models.TextField(blank=True, default='')),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('completed_units', models.PositiveIntegerField(default=0)),
                ('unit_label', models.CharField(blank=True, default='', max_length=40)),
                ('minutes_per_unit', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='curriculum.learninggoal')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='courseplan',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_plans', to='curriculum.studymaterial'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['user_email', 'goal'], name='curriculum__user_em_6bc270_idx'),
        ),
    ]
