# Generated by Django 5.1.6 on 2026-01-04 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_learningprogram_user_email'),
        ('mind', '0004_add_order_index_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicplan',
            name='planned_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='practice_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='review1_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='review2_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicplan',
            name='theory_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='hours_planned',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('THEORY', 'Theory - Initial Learning'), ('PRACTICE', 'Practice - Exercises'), ('REVIEW', 'Review - Spaced Repetition'), ('TEST', 'Test - Knowledge Check')], default='THEORY', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.CharField(default='08:00', max_length=5)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('day_number', models.IntegerField(default=1)),
                ('order_in_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='SCHEDULED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('topics_covered', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='ai_engine.learningprogram')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_study_sessions', to='mind.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_study_sessions', to='mind.topic')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time', 'order_in_day'],
            },
        ),
    ]
