# Generated by Django 5.1.6 on 2026-01-04 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0003_add_study_sessions"),
        ("mind", "0004_add_order_index_to_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectDeadline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "scope_mode",
                    models.CharField(
                        choices=[
                            ("UP_TO_TOPIC", "Learn up to specific topic"),
                            ("ALL_TOPICS", "Learn all topics"),
                        ],
                        default="ALL_TOPICS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_deadlines",
                        to="ai_engine.learningprogram",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_deadlines",
                        to="mind.subject",
                    ),
                ),
                (
                    "target_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadline_milestones",
                        to="mind.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "subject")},
            },
        ),
    ]
