# Generated by Django 6.0 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_aiusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('messages', models.JSONField(default=list)),
                ('lesson_plan', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_email', 'updated_at'], name='ai_engine_c_user_em_20e62e_idx')],
            },
        ),
    ]
