# Generated by Django 6.0 on 2026-07-27 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_chatsession'),
        ('mind', '0004_add_order_index_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='goal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='help_profile',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='hint_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='skill_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='mind.topic'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('skill_ref', models.CharField(blank=True, default='', max_length=255)),
                ('activity', models.CharField(choices=[('explanation', 'Объяснение'), ('task_attempt', 'Попытка решения'), ('practice', 'Практика'), ('review', 'Повторение'), ('diagnostic', 'Диагностика'), ('contest', 'Контест'), ('hint', 'Подсказка')], default='explanation', max_length=32)),
                ('mode', models.CharField(blank=True, default='', max_length=32)),
                ('task_ref', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(choices=[('correct', 'Верно'), ('incorrect', 'Неверно'), ('partial', 'Частично'), ('skipped', 'Пропущено'), ('abandoned', 'Брошено'), ('completed', 'Завершено')], default='completed', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('hint_level', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('error_type', models.CharField(blank=True, choices=[('misread_problem', 'Неверно понял условие'), ('wrong_formula', 'Выбрал неверную формулу'), ('missing_prerequisite', 'Не знает prerequisite'), ('arithmetic', 'Арифметическая ошибка'), ('sign_error', 'Ошибка знака'), ('units', 'Потерял единицы измерения'), ('incomplete', 'Правильный метод, но не завершил'), ('guessed', 'Угадал'), ('copied', 'Списал'), ('out_of_time', 'Не уложился по времени'), ('unknown', 'Не удалось определить')], default='', max_length=32)),
                ('confidence_before', models.FloatField(blank=True, null=True)),
                ('confidence_after', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='mind.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email', 'created_at'], name='learn_evt_user_created_idx'), models.Index(fields=['user_email', 'topic'], name='learn_evt_user_topic_idx'), models.Index(fields=['mode', 'created_at'], name='learn_evt_mode_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Не начато'), ('LEARNING', 'Изучаю'), ('NEEDS_PRACTICE', 'Нужна практика'), ('MASTERED', 'Усвоено'), ('DUE_REVIEW', 'Пора повторить')], default='NOT_STARTED', max_length=20)),
                ('mastery_probability', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('avg_hint_level', models.FloatField(default=0.0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('common_errors', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_states', to='mind.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['user_email', 'status'], name='skill_state_user_status_idx'), models.Index(fields=['user_email', 'next_review_at'], name='skill_state_user_due_idx')],
                'unique_together': {('user_email', 'topic')},
            },
        ),
    ]
