# Generated by Django 6.0 on 2026-07-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_chatsession_attempt_count_chatsession_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='canvas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
