# Generated by Django 6.0 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0008_chatsession_canvas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageQuotaState",
            fields=[
                (
                    "user_email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reservations", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
