# Generated by Django 6.0 on 2026-01-02 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SrsReviewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.CharField(max_length=255)),
                ("rating", models.CharField(max_length=10)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("interval_days_after", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("emoji", models.CharField(default="📚", max_length=10)),
                ("color", models.CharField(default="#8b5cf6", max_length=9)),
                ("target_hours_week", models.FloatField(default=5)),
                ("textbook_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("END_OF_CHAPTER", "End of Chapter"),
                            ("CROSS_TOPIC", "Cross Topic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sets",
                        to="mind.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SrsState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=20)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("interval_days", models.IntegerField(blank=True, null=True)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("mastery", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_set",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_state",
                        to="mind.reviewset",
                    ),
                ),
                (
                    "subtopic",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_state",
                        to="mind.subtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("MEDIUM", "Medium"),
                            ("SUCCESS", "Success"),
                            ("MASTERED", "Mastered"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "study_state",
                    models.CharField(
                        choices=[
                            ("STUDIED", "Studied"),
                            ("NOT_STUDIED", "Not Studied"),
                        ],
                        default="NOT_STUDIED",
                        max_length=20,
                    ),
                ),
                ("picked", models.BooleanField(default=False)),
                ("order_index", models.IntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("last_revised_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("interval_days", models.IntegerField(blank=True, null=True)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="mind.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="mind.topic",
            ),
        ),
        migrations.AddField(
            model_name="reviewset",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_sets",
                to="mind.topic",
            ),
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.CharField(max_length=10)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("interval_days_after", models.IntegerField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="mind.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MindSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("breaks_minutes", models.IntegerField(default=0)),
                ("total_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="mind.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSetLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="mind.reviewset",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_set_links",
                        to="mind.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("review_set", "topic")},
            },
        ),
    ]
