# Generated by Django 6.0 on 2026-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind", "0003_subject_user_email_mindsession_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="order_index",
            field=models.IntegerField(default=0),
        ),
    ]
